#!/bin/bash

OPENBC=/var/www/openbc
export PERL5LIB="$OPENBC/lib"

exec 2>&1 \
    /usr/local/bin/starman --listen 127.0.0.1:2080 --workers 4 --preload-app \
        --user openbc --group www-data \
        $OPENBC/etc/production.psgi >> /var/log/openbc-server.log 2>&1
